GET http://localhost:80/api/tree

Content-Type: application/json

### get tree by id
GET http://localhost:80/api/tree/6262fc97055f859d25272b8f

Content-Type: application/json

### post tree

POST http://localhost:80/api/tree
Content-Type: application/json

{
    "name": "Machine Learning A-Z™: Hands-On Python & R In Data Science udemy",
    "description": "Machine Learning A-Z™: Hands-On Python & R In Data Science",
    "imageurl": "https://img-b.udemycdn.com/course/240x135/950390_270f_3.jpg"

}
### add course to tree

PATCH http://localhost:80/api/tree/626459e97eded5218d4fa0ef
Content-Type: application/json

{
 "courseId": "625dddfba1b38a6763764936"
}

### delete course from tree


# DELETE http://localhost:80/api/tree/6262f6d3c44667b757bc87f3

# Content-Type: application/json

# {
#  "courseId": "625dddfba1b38a6763764936"
# }

### delete tree

DELETE http://localhost:80/api/tree/62634a47cf933e2e6f203dac



